export const deliverableConfig = {
    deliverableTitle: "Project Deliverable Ttile",
    deliverableTitleCreateSuccess: "Your Deliverable Title has been created successfully!!!",
    deliverableTitleCreateError: "Your Deliverable Title couldn't be created",
    deliverableTitleUpdateSuccess: "Your Deliverable Title has been updated successfully!!!",
    deliverableTitleUpdateError: "Ypur Deliverable Title couldn't be updated",
    deliverableDescriptionCreateSuccess: "Your Deliverable description has been created successfully!!!",
    deliverableDescriptionCreateError: "Your Deliverable description couldn't be created",
    deliverableDescriptionUpdateSuccess: "Your Deliverable description has been updated successfully!!!",
    deliverableDescriptionUpdateError: "Ypur Deliverable description couldn't be updated",
    deliverableDueDateCreateSuccess: "Your Deliverable due date has been created successfully!!!",
    deliverableDueDateCreateError: "Your Deliverable due date couldn't be created",
    deliverableDueDateUpdateSuccess: "Your Deliverable due date has been updated successfully!!!",
    deliverableDueDateUpdateError: "Ypur Deliverable due date couldn't be updated",
    deliverableReorderSuccess: "Your Deliverable list has been successfully reordered",
    deliverableReorderError: "Your Deliverable couldn't be reordered",
    deliverableStatusSuccess: "Your Deliverable has been successfully completed",
    deliverableStatusrError: "Your Deliverable couldn't be completed let's try that again",
    deliverableDeleteSuccess: "Your Deliverable has been deleted completed",
    deliverableDeleteError: "Your Deliverable couldn't be deleted let's try that again",

    userNamePlaceholder: "Your username",
    email: "Email",
    emailPlaceholder: "Your email",
    website: "Website",
    websitePlaceholder: "https://your-website.com",
    update: "Update Profile",
    changeLogo: "Change Logo",
    uploadNote: "JPG, GIF or PNG. 5MB max.",
    pleaseWait: "Please wait...",
    successMessage: "Your profile has been updated.",
    errorMessage: "Error has been occured by updating your profile.",
    successNameMessage: "Your Business Name has been updated.",
    errorNameMessage: "Error has been occured by updating your Business Name.",
  };
  