export const financeConfig = {
    ConnectStrioe: "Connect Stripe",
    pleaseWait: "Please wait...",
    stripeConnectSuccess: "Stripe connected successfully",
    stripeConnectError: "Couldn't connect your Stripe account, Retry",
    stripeDisconnectSuccess: "Stripe account diconnected successfully",
    stripeDisconnectError: "Couldn't connect your Stripe account, Retry",
    paypalConnectSuccess: "Paypal connected successfully",
    paypalConnectError: "Couldn't connect your Paypal account, Retry",
    paypalDisconnectSuccess: "Paypal account diconnected successfully",
    paypalDisconnectError: "Couldn't connect your Paypal account, Retry",
    lemonsqueezyConnectSuccess: "LemonSqueezy connected successfully",
    lemonsqueezyConnectError: "Couldn't connect your LemonSqueezy account, Retry",
    lemonsqueezyDisconnectSuccess: "LemonSqueezy account diconnected successfully",
    lemonsqueezyDisconnectError: "Couldn't connect your LemonSqueezy account, Retry",
    paystackConnectSuccess: "Paystack connected successfully",
    paystackConnectError: "Couldn't connect your Paystack account, Retry",
    paystackDisconnectSuccess: "Paystack account diconnected successfully",
}