export const profileConfig = {
    primaryTitle: "Personal information",
    primarySubTitle: "Update your personal information.",
    secondaryTitle: "User information",
    secondarySubTitle: "Update your user information",
    formImageNote: "Only JPG, PNG files are allowed. 5MB max.",
    successMessageImageUpload: "Your image was uploaded successfully.",
    errorMessageImageUpload: "Couldn't upload your image.",
    name: "Fullname",
    businessName: "Business Name",
    businessNamePlaceholder: "Your Business Name",
    businessEmail: "Business Email",
    businessEmailPlaceholder: "Your Business Email",
    businessMobile: "Business Mobile",
    businessMobilePlaceholder: "Your Business Mobile",
    businessAddress: "Business Address",
    businessAddressPlaceholder: "Your Business Address",
    userName: "Username",
    userNamePlaceholder: "Your username",
    email: "Email",
    emailPlaceholder: "Your email",
    website: "Website",
    websitePlaceholder: "https://your-website.com",
    update: "Update Profile",
    changeLogo: "Change Logo",
    uploadNote: "JPG, GIF or PNG. 5MB max.",
    pleaseWait: "Please wait...",
    successMessage: "Your profile has been updated.",
    errorMessage: "Error has been occured by updating your profile.",
    successNameMessage: "Your Business Name has been updated.",
    errorNameMessage: "Error has been occured by updating your Business Name.",
  };
  