export const projectConfig = {
    projectCreateSuccess: "Project has been created successfully",
    projectCreateError: "Couldn't create project, Let's try that again",
    projectNameUpdateSuccess: "Project Name has been updated successfully",
    projectNameUpdateError: "Couldn't update Project Name, Let's try that again",
    projectDescriptionUpdateSuccess: "Project Description has been updated successfully",
    projectDescriptionUpdateError: "Couldn't update Project Description, Let's try that again",
    projectClientUpdateSuccess: "Project Client has been updated successfully",
    projectClientUpdateError: "Couldn't update Project Client, Let's try that again",
    projectDeleteSuccess: "Project has been deleted successfully",
    projectDeleteError: "Couldn't delete Project, Let's try that again",
    projectAmountSuccess: "Project Amount has been updated successfully",
    projectAmountError: "Couldn't update Project Amount, Let's try that again",
    projectStatusSuccess: "Project status has been updated successfully",
    projectStatusError: "Couldn't update Project status, Let's try that again",
    projectInvoiceSuccess: "Invoice initiated successfully",
    projectInvoiceError: "Couldn't initiate project invoice, Let's try that again",
    primarySubTitle: "Update your personal information.",
    secondaryTitle: "User information",
    secondarySubTitle: "Update your user information",
    formImageNote: "Only JPG, PNG files are allowed. 5MB max.",
    successMessageImageUpload: "Your image was uploaded successfully.",
    errorMessageImageUpload: "Couldn't upload your image.",
    name: "Fullname",
    businessName: "Business Name",
    businessNamePlaceholder: "Your Business Name",
    businessEmail: "Business Email",
    businessEmailPlaceholder: "Your Business Email",
    businessMobile: "Business Mobile",
    businessMobilePlaceholder: "Your Business Mobile",
    businessAddress: "Business Address",
    businessAddressPlaceholder: "Your Business Address",
    userName: "Username",
    userNamePlaceholder: "Your username",
    email: "Email",
    emailPlaceholder: "Your email",
    website: "Website",
    websitePlaceholder: "https://your-website.com",
    update: "Update Profile",
    changeLogo: "Change Logo",
    uploadNote: "JPG, GIF or PNG. 5MB max.",
    pleaseWait: "Please wait...",
    successMessage: "Your profile has been updated.",
    errorMessage: "Error has been occured by updating your profile.",
    successNameMessage: "Your Business Name has been updated.",
    errorNameMessage: "Error has been occured by updating your Business Name.",
  };
  